import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"], // Or other subsets as needed
  weight: "400", // Or other weights like '700', 'regular', etc.
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap", // Important for performance
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body className={` antialiased`}>{children}</body>
    </html>
  );
}
